//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto_Inter
{
    using System;
    using System.Collections.Generic;
    
    public partial class cotacao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cotacao()
        {
            this.compra = new HashSet<compra>();
        }
    
        public int idcotacao { get; set; }
        public System.DateTime datacotacao { get; set; }
        public int idreq { get; set; }
        public System.DateTime datareq { get; set; }
        public string funcioanriosolicit { get; set; }
        public string departamento { get; set; }
        public string valor { get; set; }
        public string funcionarioaprov { get; set; }
        public int idfuncionario { get; set; }
    
        public virtual cadastro_funcionario cadastro_funcionario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<compra> compra { get; set; }
        public virtual requisicao requisicao { get; set; }
    }
}
